services:
  - type: web
    name: mandiuslinkbot
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: BOT_TOKEN
  value: 7801325768:AAGZq3yq9fTpapCgIj1Hc3nE7M2T5F2Vcow
      - key: RENDER_EXTERNAL_URL
        value: https://mandiuslinkbot.onrender.com
      
